### ISSUE TITLE
How to Build?

### ISSUE THREAD

**Issue by Gosokan** [JustAMan/ffmpeg-standalone-build#1]
Hello,

Can you give a guide for build ffmpeg from your repo? I'm using ubuntu 18.04.

**Comment by JustAMan** [comment]
First, a warning - I didn't check that "redistributable" build is okay (and it probably isn't, as openssl should break without `--enable-nonfree` but I haven't checked) as I only ever used non-redistributable one. This is because when certain flags (like `--enable-nonfree` and `--enable-gpl`) are used together the ending binary has conflicting licenses, which means you cannot distribute the bits.
So as long as you plan to only use it yourself, follow along, otherwise wait for me to fix it further.

Now for the instructions, they should be pretty simple:
1) `git clone https://github.com/JustAMan/ffmpeg-standalone-build.git`
2) `cd ffmpeg-standalone-build && git submodule update --init --recursive`
3) `make ENABLE_NOGPL=yes`, confirm that you're okay with non-redistributable package
4) copy resulting `ffmpeg.tgz` anywhere - you can unpack it in any place and it should work there

If anything goes wrong please report.
